I started with the wrong exercise: 100 Numpy Exercises

In [ ]:
#1. Import the numpy package
import numpy as np

In [15]:
#2. To check which version
np.version.version 

'1.20.1'

In [16]:
#2. To show the configuration 
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Applications/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Applications/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Applications/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Applications/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Applications/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Applications/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Applications/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Applications/anaconda3/include']


In [19]:
# 3. Create a null vector of size 10
x = np.zeros(10)

In [20]:
# 4. To find the memory size of any array
print("%d bytes" % (x.size * x.itemsize))

80 bytes


In [17]:
#5. documentatoin of the numpy add function from the command line
%run 'python -c "import numpy; numpy.info(numpy.add)"'

Exception: File `'python -c "import numpy; numpy.info(numpy.add)".py'` not found.

In [25]:
#6. To create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[5] = 1
y

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [26]:
#7. To create a vector with values ranging from 10 to 49 
# Be careful that the range includes 49.
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
#8. To reverse a vector
y[::-1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [34]:
#9. To create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#10 To find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [38]:
#11. To create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
#12. To create a 3x3x3 array with random values
#Important: Put more than one value in two parantheses
np.random.random((3,3,3))

array([[[0.53828224, 0.74485754, 0.38351639],
        [0.24127624, 0.22037613, 0.79274123],
        [0.32930255, 0.30590131, 0.55233435]],

       [[0.00873229, 0.85840292, 0.17226103],
        [0.46904898, 0.1853788 , 0.25057998],
        [0.00276748, 0.79228632, 0.54571654]],

       [[0.09282286, 0.82285705, 0.78496833],
        [0.4236024 , 0.45931054, 0.13064698],
        [0.37873868, 0.61733235, 0.71715462]]])

In [48]:
#13. To create a 10x10 array with random values and find the minimum and maximum values
z = np.random.random((10,10))
z.min()
z.max()

0.9928639369455603

In [53]:
#14. To create a random vector of size 30 and find the mean value
r= np.random.random(30)
mean = r.mean()
mean

0.4760275332741364

In [60]:
#15. To create a 2d array with 1 on the border and 0 inside
#First create a 2d array with only ones with the np.ones()
#Then replace the inside with 0
o = np.ones((10,10))
o[1:-1, 1:-1] = 0
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
#16. To add a border (filled wiht 0's) around an existing array
z = np.ones((8,8))
z = np.pad(z,pad_width=1, mode='constant', constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
#17. What is the result of the following expression?
(0 * np.nan) #result: Nan
np.nan == np.nan #result: False
np.inf > np.nan #result: False
np.nan - np.nan #result: nan
np.nan in set([np.nan]) #result: True
0.3 == 3 * 0.1 #result: False

False

In [79]:
#18. To create a 5x5 matrix with values 1,2,3,4 just below the diagonal
i = np.diag(1+np.arange(4), k=-1)
i

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [85]:
#19. To create a 8x8 matrix and fill it with a checkerboard pattern
j = np.zeros((8,8))
j[1::2,::2] = 1
j[::2,1::2] = 1
j

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [93]:
#20. To consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
p = np.random.random((6,7,8))
print(p)
np.unravel_index(99,(6,7,8))

[[[0.45856688 0.77608358 0.77785525 0.90341024 0.01605974 0.83635491
   0.19025242 0.85646858]
  [0.96126705 0.80011462 0.08455655 0.75328619 0.51307425 0.0248107
   0.94723049 0.53727614]
  [0.55202756 0.89922313 0.33340759 0.13177722 0.64878083 0.33643763
   0.96579013 0.28594876]
  [0.33737706 0.63286828 0.57868509 0.92675229 0.6767784  0.7969442
   0.46376562 0.13635542]
  [0.24677351 0.34078555 0.63576225 0.24912268 0.02381279 0.23707548
   0.40184351 0.92995106]
  [0.30960454 0.65668479 0.46215188 0.40335566 0.35097906 0.46315261
   0.32457628 0.6821496 ]
  [0.67298907 0.95284395 0.02891396 0.34813873 0.68462034 0.81010356
   0.88094842 0.85018992]]

 [[0.56219497 0.67470127 0.38603538 0.3935728  0.51191432 0.43502059
   0.86037331 0.0083164 ]
  [0.84645946 0.65709889 0.72950071 0.57602391 0.03298486 0.82412897
   0.92013786 0.90763898]
  [0.82240081 0.18367739 0.03854627 0.34821525 0.582697   0.03818104
   0.10104139 0.84408252]
  [0.07138892 0.42596753 0.5534278  0.22261987 0.3

(1, 5, 3)

In [112]:
#21 To create a checkerboard 8x8 matrix using the tile function
k = np.tile( np.array([[0,1], [0,1]]), (4,4))
k

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [115]:
#22 To normalize a 5x5 random matrix
u = np.random.random((5,5))
u = (u - np.mean (u)) / (np.std (u))
u

array([[ 1.28490274,  0.083201  , -0.94554937,  0.78737999, -0.62752522],
       [ 1.1084234 , -1.4928122 , -0.47443158,  0.35356672,  0.5552679 ],
       [ 0.92418206, -0.39061914, -0.86652135,  0.59762185, -0.65145006],
       [ 0.45300418, -0.2435767 , -1.29180771, -0.87037555, -1.58564589],
       [-0.9269439 ,  2.26233451, -0.24323259,  1.84752024,  0.35308667]])

In [121]:
#23. To create a custom dtype that describes a color as four unsigned bytes (RGBA)
colour = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])
colour

<ipython-input-121-09f0ae7d3a4b>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  colour = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [127]:
#24. To multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

t = np.dot(np.ones((5,3)), np.ones((3,2)))
t

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [133]:
#25. To give a 1D array, negate all elements which are between 3 and 8, in place.
u = np.arange(10)
u[(3 < u) & (u < 8)] *= -1
u

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [135]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) #it sums it 

9
10


In [143]:
#27. Consider an integer vector Z, which of these expressions are legal?
Z = np.array(11)
Z**Z #result: 285311670611
2 << Z >> 2 #result: 1024
Z <- Z #result: False
1j*Z #result: 11j
Z/1/1 #result: 11.0
Z<Z>Z #result: False

False

In [148]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0) #result: nan
np.array(0) // np.array(0) #result: 0
np.array([np.nan]).astype(int).astype(float) #result: array([-9.22337204e+18])

<ipython-input-148-e03d300d79e7>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0) #result: nan
<ipython-input-148-e03d300d79e7>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) #result: 0


array([-9.22337204e+18])

In [153]:
#29. To round away from zero a float array
e = np.random.uniform(-15, 10, 15)
np.copysign(np.ceil(np.abs(e)), e)

array([ -9.,   6.,   2.,   1., -15.,   5., -15.,  10.,  -3.,  10.,   3.,
       -10.,   7.,  10.,   7.])

In [154]:
#30. How to find common values between two arrays?
p1 = np.random.randint(0,10,10)
p2 = np.random.randint(0,10,10)
np.intersect1d(p1,p2)

array([0, 5, 7, 9])

In [159]:
#31. How to ignore all numpy warnings(not recommended)?
o = np.seterr(all="ignore")
np.seterr(**o)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [161]:
#32. Is the following expression true?
np.sqrt(-1) == np.emath.sqrt(-1) #result: False

False

In [172]:
#33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
print(today)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2022-01-13
2022-01-12
2022-01-14


In [177]:
#34. How to get all the dates corresponding to the month of July 2016?
july = np.arange('2016-07', '2016-08', dtype= 'datetime64[D]')
july

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [ ]:
#35. How to compute ((A+B)*(-A/2))) in place (without copy)?

Here I realized that the lab is that:

In [ ]:
#1. Import the numpy package
import numpy as np

In [178]:
# 2. Create a null vector of size 10
zeros = np.zeros(10)

In [181]:
# 3. Create a null vector of size 10 but the fifth value which is 1
zeros[4]=1
print(zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [183]:
# 4. Create a vector with values ranging form 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [185]:
#5. Create a 3x3 matrix with valuse ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [187]:
#6. Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [189]:
#7. Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
#8. Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.33318673, 0.42722224, 0.1398876 ],
        [0.66536943, 0.26006691, 0.37656424],
        [0.68714618, 0.21016568, 0.52752549]],

       [[0.38384841, 0.92604937, 0.53825125],
        [0.1640066 , 0.80516989, 0.62787271],
        [0.13890263, 0.67892846, 0.44153217]],

       [[0.43655232, 0.11887816, 0.52552353],
        [0.47470312, 0.44904073, 0.67876118],
        [0.39059836, 0.85745336, 0.87187386]]])

In [202]:
#9. Create a 10x10 array with random values and find the minimum and maximum
z = np.random.random((10,10))
z.min()
z.max()

0.9956684788364594

In [205]:
#10. Create a random vector of size 30 and find the mean value
r = np.random.random(30)
r.mean()

0.44695351569870606

In [207]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
#18. To create a 5x5 matrix with values 1,2,3,4 just below the diagonal
i = np.diag(1+np.arange(4), k=-1)
i

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [209]:
#12. To normalize a 5x5 random matrix
u = np.random.random((5,5))
u = (u - np.mean (u)) / (np.std (u))
u

array([[ 0.26450124,  1.39644308, -0.80292125,  1.14429012, -0.36704867],
       [ 2.08268382,  1.08713957, -1.21093255, -0.73799867, -0.68865005],
       [ 1.08914978, -0.24782547, -0.8427204 , -1.11855448,  0.06633656],
       [ 1.82400952, -0.3817449 , -0.5049549 , -0.45480327, -0.94977309],
       [-0.32277765, -0.4294826 ,  1.76025193, -0.62675085, -1.02786683]])

In [210]:
#13. How to find common values between two arrays?
p1 = np.random.randint(0,10,10)
p2 = np.random.randint(0,10,10)
np.intersect1d(p1,p2)

array([1, 4, 5, 9])

In [216]:
#14.Create a random vector of size 10 and sort it
v = np.random.random(10)
v.sort()
v

array([0.15787638, 0.21674383, 0.24085596, 0.34095554, 0.42330825,
       0.44516651, 0.48484098, 0.74321072, 0.79160715, 0.7919874 ])

In [232]:
#15. Create random vector of size 10 and replace the maximum value by 0
g = np.random.random(10)
g.argmax()
g[g.argmax()]=0
g

array([0.13606269, 0.08318604, 0.53291622, 0.11927758, 0.        ,
       0.53060197, 0.91170736, 0.90338426, 0.60318329, 0.76663439])

In [235]:
#16. Subtract the mean of each row of a matrix
z = g - g.mean(axis=0, keepdims=True)
z

array([-0.32263269, -0.37550934,  0.07422084, -0.3394178 , -0.45869538,
        0.07190659,  0.45301198,  0.44468888,  0.14448791,  0.30793901])

In [239]:
#17. How to get the n largest values of an array
H = np.arange(10000)
np.random.shuffle(H)
n = 5

H[np.argpartition(-H,n)[:n]] 

H[np.argsort(H)[-n:]]

array([9995, 9996, 9997, 9998, 9999])

In [245]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares

s = np.random.random(5*3)
s[:] > 4 *= 2

SyntaxError: cannot assign to comparison (<ipython-input-245-74172304c136>, line 4)